CREATE TABLE contacts (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  firstname TEXT NOT NULL,
  lastname TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  streetnum INTEGER NOT NULL,
  streetname TEXT NOT NULL,
  city TEXT NOT NULL,
  zip TEXT NOT NULL,
  request_service BOOLEAN NOT NULL DEFAULT 'no',
  request_news BOOLEAN NOT NULL DEFAULT 'no',
  volunteer BOOLEAN NOT NULL DEFAULT 'no'
);
