CREATE TYPE star_rating AS ENUM ('1', '2', '3', '4', '5');

CREATE TABLE bookmarks (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  lastname TEXT NOT NULL,
  url TEXT NOT NULL,
  streetnum INTEGER NOT NULL,
  streetname TEXT NOT NULL,
  city TEXT NOT NULL,
  zip INTEGER NOT NULL,
  description TEXT,
  rating star_rating NOT NULL
);
